### PR TITLE
resolves #28 set base_dir correctly by using Asciidoctor#convertFile

### LINKED ISSUE #28: base_dir is not set correctly when using the asciidoctorjs command
The base_dir does not seems to be set correctly when using the asciidoctorjs command. Assets are being resolved relative to the current directory instead of from the document directory.

Follow these steps to reproduce:

1. Create a src directory
2. Add an image to the src directory
3. Create the AsciiDoc file test.adoc in the src directory that references an image named tiger.png

    ```
    = Document Title

    image::tiger.png[]
    ```

4. Change to the parent directory of src
5. Convert the AsciiDoc file in src with the data-uri attribute set

    ```
    asciidoctorjs -a data-uri src/test.adoc
    ```
6. Observe the message: asciidoctor: WARNING: image to embed not found or not readable

This command works if you run it from the src directory. It also works if you set the base_dir to src (`-B src`).

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

File: lib/cli.js [hunk 1]
```diff
@@ -139,8 +106,15 @@ function run () {
...
     } else {
       cliArgs.forEach(function (file) {
-        var data = convertFile(file, options);
-        outputResult(data, file, cliOptions);
+        cli.debug('converting file ' + file);
+        if (options.timings) {
+          var timings = asciidoctor.Timings.$new();
+          var instanceOptions = Object.assign({}, options, { timings: timings })
+          asciidoctor.convertFile(file, instanceOptions);
+          timings.$print_report(Opal.gvars.stderr, file);
```
Comment (Mogztter) [inline lib/cli.js]: It should be `stdout` no ? By default the `print_report` is using `stdout` in core: https://github.com/asciidoctor/asciidoctor/blob/25ca4dafc34d733f5f9c1e723038f93386c318ba/lib/asciidoctor/timings.rb#L50

File: asciidoctor.css [hunk 2]
```diff
@@ -1,409 +0,0 @@
-/* Asciidoctor default stylesheet | MIT License | http://asciidoctor.org */
```
Comment (Mogztter) [inline asciidoctor.css]: I'm guessing that this file is not used anymore (it was somehow useful when we were using `convert` instead of `convertFile`, right ?

File: lib/cli.js (hunk 1 above)
Comment (mojavelinux) [reply lib/cli.js]: The CLI overrides this. See https://github.com/asciidoctor/asciidoctor/blob/25ca4dafc34d733f5f9c1e723038f93386c318ba/lib/asciidoctor/cli/invoker.rb#L124

Otherwise, the output gets mixed with the document piped to stdout.

File: asciidoctor.css (hunk 2 above)
Comment (mojavelinux) [reply asciidoctor.css]: Correct. This is now satisfied by asciidoctor.js.
